import { StyleSheet } from "@react-pdf/renderer";
import { PDF_PAGE_HEIGHT, PDF_PAGE_WIDTH } from "../theme";
import { LD } from "./lockedDesignTokens";

/**
 * Locked report: editorial hierarchy — rules, type contrast, minimal containment.
 */
export const lockedStyles = StyleSheet.create({
  cover_page: {
    width: PDF_PAGE_WIDTH,
    height: PDF_PAGE_HEIGHT,
    fontFamily: LD.font.sans,
    backgroundColor: LD.color.paper,
    position: "relative",
  },
  /** Full-bleed column: agency (top) → hero → client → flex → date (foot). */
  cover_root: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "column",
    paddingHorizontal: LD.space.xxxl,
    paddingTop: 88,
    paddingBottom: 64,
  },
  cover_agency: {
    alignSelf: "flex-start",
    width: "100%",
    marginBottom: LD.space.sm,
  },
  cover_agencyText: {
    fontSize: LD.size.coverAgency,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    letterSpacing: 0.18,
    textTransform: "none",
    textAlign: "left",
    lineHeight: LD.lineHeight.normal,
  },
  cover_titleCluster: {
    width: "100%",
    alignItems: "center",
    marginTop: 52,
  },
  cover_rule: {
    width: 56,
    height: LD.border.accentRule,
    backgroundColor: LD.color.ink,
    marginBottom: LD.space.lg,
    alignSelf: "center",
  },
  cover_title: {
    fontSize: LD.size.coverPoster,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    textAlign: "center",
    letterSpacing: -1.35,
    lineHeight: LD.lineHeight.tight,
    maxWidth: "100%",
    width: "100%",
  },
  cover_client: {
    fontSize: LD.size.coverClient,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    textAlign: "center",
    lineHeight: LD.lineHeight.snug,
    width: "100%",
    marginTop: 36,
  },
  cover_spacer: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 48,
  },
  cover_date: {
    fontSize: LD.size.coverDate,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    textAlign: "center",
    lineHeight: LD.lineHeight.relaxed,
    letterSpacing: 0.08,
    width: "100%",
    paddingTop: LD.space.sm,
  },

  /* ——— Narrative stack (argument spine on every page) ——— */
  nar_stack: {
    marginBottom: LD.space.lg,
    paddingBottom: LD.space.sm,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  nar_stackAfter: {
    marginTop: LD.space.md,
    marginBottom: 0,
    paddingTop: LD.space.sm + 2,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.rule,
  },
  nar_stackPlain: {
    marginTop: 0,
    marginBottom: 0,
    paddingTop: 0,
    paddingBottom: 0,
    borderTopWidth: 0,
    borderBottomWidth: 0,
  },
  nar_stackCompact: {
    marginBottom: LD.space.sm + 2,
  },
  nar_stackCover: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  nar_headline: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.22,
    lineHeight: LD.lineHeight.tight,
    marginBottom: LD.space.sm + 2,
  },
  nar_headlineCompact: {
    fontSize: LD.size.titleSm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.12,
    lineHeight: LD.lineHeight.snug,
    marginBottom: LD.space.xs + 2,
  },
  nar_interpretation: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.xs + 2,
  },
  nar_interpretationCompact: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.normal,
    marginBottom: LD.space.xs,
  },
  nar_implication: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.editorial,
    marginBottom: LD.space.xs,
  },
  nar_implicationCompact: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.normal,
    marginBottom: 0,
  },
  nar_action: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    marginTop: LD.space.xxs,
  },
  nar_actionCompact: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    marginTop: LD.space.xxs,
  },
  perf_section: {
    width: "100%",
    marginBottom: LD.space.lg,
    paddingBottom: LD.space.md,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  perf_sectionTight: {
    width: "100%",
    marginBottom: LD.space.xxl,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  perf_sectionDiagnosis: {
    width: "100%",
    marginTop: LD.space.xl,
    marginBottom: LD.space.lg,
    paddingTop: LD.space.sm,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  perf_sectionEyebrow: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.md,
  },
  perf_heroVerdictTitle: {
    fontSize: 19,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    letterSpacing: -0.12,
    marginBottom: LD.space.lg,
    maxWidth: "100%",
  },
  perf_heroTakeawayWrap: {
    maxWidth: 300,
    paddingLeft: LD.space.md,
    marginBottom: LD.space.xl,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.ink3,
  },
  perf_heroTakeaway: {
    fontSize: 9.5,
    fontFamily: LD.font.sans,
    color: LD.color.ink,
    lineHeight: 1.58,
    maxWidth: "100%",
  },
  perf_heroRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 0,
  },
  perf_heroDial: {
    width: 192,
    marginRight: LD.space.xl,
    alignItems: "center",
  },
  perf_heroAside: {
    flex: 1,
    justifyContent: "center",
    paddingVertical: LD.space.sm,
  },
  perf_metricHelp: {
    fontSize: 8,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.relaxed,
    marginTop: LD.space.sm,
    maxWidth: "100%",
  },
  perf_miniBarTrack: {
    flexDirection: "row",
    height: 5,
    marginTop: LD.space.xs,
    width: "100%",
  },
  perf_miniBarFill: { height: 5 },
  perf_miniBarRest: { height: 5, backgroundColor: LD.color.rule },
  perf_diagWrap: {
    width: "100%",
    marginTop: 0,
    paddingTop: 0,
  },
  perf_diagNarrativeWrap: {
    maxWidth: "100%",
    paddingLeft: LD.space.md,
    paddingVertical: LD.space.sm,
    borderLeftWidth: LD.border.accentRule,
    borderLeftColor: LD.color.ink,
  },
  perf_diagNarrative: {
    fontSize: 9.5,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: 1.6,
    maxWidth: "100%",
  },
  perf_diagNarrativeGap: {
    marginBottom: LD.space.lg,
  },
  nar_inaction: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.editorial,
    marginTop: LD.space.xs,
  },

  eyebrow: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  sectionTitle: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.2,
    marginBottom: LD.space.sm,
  },
  bandCaption: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.editorial,
    marginBottom: LD.space.md,
    maxHeight: 28,
  },
  bandCaptionLead: {
    fontSize: LD.size.body,
    fontFamily: LD.font.sans,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.md,
    maxHeight: 32,
  },
  body: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
  },
  bodyMuted: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  bodyQuiet: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  caption: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
  },
  labelStrong: {
    fontSize: LD.size.label,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
  },

  divider: {
    height: LD.border.hairline,
    backgroundColor: LD.color.rule,
    marginVertical: LD.space.sm,
  },
  dividerStrong: {
    height: LD.border.accentRule,
    backgroundColor: LD.color.ink,
    marginVertical: LD.space.md,
  },

  card: {
    backgroundColor: LD.color.paper,
    borderWidth: LD.border.hairline,
    borderColor: LD.color.ink,
    overflow: "hidden",
  },
  cardFilled: {
    backgroundColor: LD.color.paper,
    borderWidth: LD.border.hairline,
    borderColor: LD.color.rule,
    overflow: "hidden",
  },

  toc_list: {
    marginTop: LD.space.md,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.rule,
  },
  toc_row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    paddingVertical: LD.space.sm + 1,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  toc_title: {
    flex: 1,
    paddingRight: LD.space.lg,
    fontSize: LD.size.tocTitle,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    letterSpacing: -0.12,
  },
  toc_page: {
    width: 40,
    textAlign: "right",
    fontSize: LD.size.tocPage,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    letterSpacing: 0.04,
  },

  /* Performance — open hero, metrics as ruled band */
  perf_hero: {
    marginBottom: LD.space.xxxl,
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  perf_scoreMark: {
    width: 52,
    height: LD.border.accentRule,
    backgroundColor: LD.color.ink,
    marginTop: LD.space.lg,
  },
  perf_score: {
    fontSize: LD.size.commandScore,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -2.2,
    lineHeight: LD.lineHeight.tight,
  },
  perf_status: {
    fontSize: LD.size.caption,
    color: LD.color.ink3,
    marginTop: LD.space.sm,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
  },
  perf_metricsBand: {
    width: "100%",
    paddingTop: 0,
    marginBottom: 0,
  },
  perf_metricsRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  perf_metricCell: {
    flex: 1,
    paddingVertical: LD.space.md,
    paddingHorizontal: LD.space.sm,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.rule,
    justifyContent: "flex-start",
    minHeight: 76,
  },
  perf_metricCellFirst: {
    flex: 1,
    paddingVertical: LD.space.md,
    paddingHorizontal: LD.space.sm,
    borderLeftWidth: 0,
    justifyContent: "flex-start",
    minHeight: 76,
  },
  perf_metricCellLast: {
    flex: 1,
    paddingVertical: LD.space.md,
    paddingHorizontal: LD.space.sm,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.rule,
    justifyContent: "flex-start",
    minHeight: 76,
  },
  perf_metricLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  perf_metricValue: {
    fontSize: 10,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: 0,
    marginBottom: LD.space.xxs,
  },
  perf_metricValueStrong: { color: LD.color.signalStrong },
  perf_metricValueModerate: { color: LD.color.ink2 },
  perf_metricValueWeak: { color: LD.color.risk },
  perf_support: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    marginTop: LD.space.lg,
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
    maxWidth: "100%",
  },

  /* Competitive — market-share view + positions table (one visual block) */
  comp_competitiveBundle: {
    marginTop: -12,
    marginBottom: LD.space.md,
  },
  comp_topSection: {
    marginBottom: LD.space.xs,
  },
  comp_pieRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 0,
  },
  comp_pieColChart: {
    width: "52%",
    paddingRight: 0,
    flexShrink: 0,
  },
  comp_pieColAside: {
    width: "48%",
    paddingLeft: LD.space.md,
    paddingTop: 2,
    paddingBottom: 2,
    justifyContent: "center",
    maxWidth: "100%",
    borderLeftWidth: 1,
    borderLeftColor: "#E5E7EB",
    borderStyle: "solid",
  },
  comp_insightLabel: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: "#6B7280",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  comp_insightHeadline: {
    fontSize: 13.5,
    fontFamily: LD.font.sansBold,
    color: "#111111",
    lineHeight: 1.25,
    marginBottom: 10,
  },
  comp_insightBody: {
    fontSize: 10.5,
    fontFamily: LD.font.sans,
    color: "#374151",
    lineHeight: 1.55,
    maxWidth: "100%",
  },
  comp_insightBodyFollow: {
    fontSize: 10.5,
    fontFamily: LD.font.sans,
    color: "#374151",
    lineHeight: 1.55,
    maxWidth: "100%",
    marginTop: 11,
  },
  /** Pie + legend row: bounded width so legend never stacks on top of the chart. */
  comp_pieBlockRoot: {
    width: "100%",
    alignSelf: "flex-start",
  },
  comp_pieChartLegendRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  comp_pieChartWrap: {
    width: 142,
    height: 142,
    flexShrink: 0,
  },
  comp_pieChartTitle: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.06,
    textTransform: "none" as const,
    lineHeight: LD.lineHeight.snug,
    marginBottom: LD.space.xxs,
    maxWidth: "100%",
  },
  comp_pieDeltaCallout: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.normal,
    marginTop: 0,
    marginBottom: 2,
    maxWidth: "100%",
  },
  comp_pieLegendWrap: {
    marginTop: 0,
    marginLeft: 8,
    alignSelf: "center",
    width: 124,
    flexGrow: 0,
    flexShrink: 0,
  },
  comp_pieLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  comp_pieLegendRowLast: {
    marginBottom: 0,
  },
  comp_pieLegendSwatch: {
    width: 8,
    height: 8,
    marginRight: LD.space.xs + 1,
  },
  comp_pieLegendText: {
    fontSize: 8,
    fontFamily: LD.font.sans,
    color: "#111111",
    lineHeight: LD.lineHeight.normal,
    textAlign: "left",
  },
  comp_secondaryBlock: {
    marginTop: LD.space.lg,
    paddingTop: LD.space.sm + 2,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    borderStyle: "solid",
  },
  comp_positionsTitle: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "none" as const,
    marginBottom: LD.space.xs + 2,
  },
  comp_positionsTable: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderStyle: "solid",
    overflow: "hidden",
  },
  comp_positionsThRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    borderStyle: "solid",
    paddingVertical: 3,
    paddingHorizontal: 5,
    minHeight: 26,
  },
  comp_positionsThText: {
    fontSize: 10,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  comp_positionsTr: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    borderStyle: "solid",
    paddingVertical: 2,
    paddingHorizontal: 5,
    minHeight: 24,
  },
  /** Ties client row to pie green — subtle scoreboard cue. */
  comp_positionsTrClient: {
    borderLeftWidth: 2,
    borderLeftColor: "#22C55E",
    paddingLeft: 4,
    backgroundColor: "#F7FDF9",
  },
  comp_positionsRowBg: {
    backgroundColor: "#FFFFFF",
  },
  comp_positionsRowBgAlt: {
    backgroundColor: "#FAFAFA",
  },
  comp_positionsTd: {
    fontSize: 10,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: 1.35,
  },
  comp_positionsTdClient: {
    fontSize: 10,
    fontFamily: LD.font.sansBold,
    color: "#111111",
    lineHeight: 1.35,
  },
  comp_positionsColBrand: { width: "26%" },
  comp_positionsColMentions: { width: "12%" },
  comp_positionsColShare: { width: "11%" },
  comp_positionsColStrength: { width: "30%" },
  comp_positionsColStatus: { width: "21%" },
  comp_positionsTension: {
    fontSize: 8,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.snug,
    marginTop: LD.space.sm,
    marginBottom: LD.space.xs,
    maxWidth: "100%",
  },
  comp_positionsSupport: {
    fontSize: 10.5,
    fontFamily: LD.font.sans,
    color: "#374151",
    lineHeight: 1.55,
    marginTop: LD.space.xs,
    maxWidth: "100%",
  },
  comp_bottomInsightBand: {
    marginTop: LD.space.md,
    paddingTop: LD.space.sm + 2,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.ink3,
  },
  comp_bottomInsightPara: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.editorial,
    marginBottom: LD.space.md,
    maxWidth: "100%",
  },
  comp_bottomInsightParaLast: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.editorial,
    marginBottom: 0,
    maxWidth: "100%",
  },
  comp_stakesBlock: {
    marginTop: LD.space.xl,
    paddingTop: LD.space.lg,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.ink3,
    maxWidth: "100%",
  },
  comp_stakesTitle: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.sm,
  },
  comp_stakesBody: {
    fontSize: 10.5,
    fontFamily: LD.font.sans,
    color: "#374151",
    lineHeight: 1.55,
    maxWidth: "100%",
  },
  /* Model breakdown — sectioned like Performance + Competitive pages */
  model_spreadRow: {
    flexDirection: "row",
    alignItems: "stretch",
    marginTop: 0,
  },
  model_spreadDial: {
    width: 118,
    marginRight: LD.space.md,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: LD.space.md,
    paddingHorizontal: LD.space.xs,
    backgroundColor: LD.color.surface2,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderStyle: "solid",
  },
  model_spreadGapNumber: {
    fontSize: 34,
    fontFamily: LD.font.sansBold,
    color: LD.color.risk,
    letterSpacing: -0.9,
    lineHeight: 1,
  },
  model_spreadGapNumberMuted: {
    fontSize: 26,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: -0.4,
    lineHeight: 1,
  },
  model_spreadGapCaption: {
    fontSize: 8,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    textAlign: "center",
    lineHeight: LD.lineHeight.relaxed,
    marginTop: LD.space.sm,
    maxWidth: 104,
  },
  model_spreadAside: {
    flex: 1,
    paddingLeft: LD.space.md + 2,
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: "#E5E7EB",
    borderStyle: "solid",
  },
  model_spreadAsideLabel: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: "#6B7280",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  model_spreadAsideHeadline: {
    fontSize: 13,
    fontFamily: LD.font.sansBold,
    color: "#111111",
    lineHeight: 1.25,
    marginBottom: LD.space.md,
    maxWidth: "100%",
  },
  model_spreadFactsRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
    maxWidth: "100%",
  },
  model_spreadFactKey: {
    width: 82,
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  model_spreadFactVal: {
    flex: 1,
    fontSize: 10,
    fontFamily: LD.font.sans,
    color: "#374151",
    lineHeight: 1.45,
  },
  model_scoresBlock: {
    marginTop: LD.space.lg,
    paddingTop: LD.space.sm + 2,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    borderStyle: "solid",
  },
  model_scoresTitle: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "none" as const,
    marginBottom: LD.space.xs + 2,
  },
  model_scoresTable: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderStyle: "solid",
    overflow: "hidden",
  },
  model_scoresThRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    borderStyle: "solid",
    paddingVertical: 3,
    paddingHorizontal: 5,
    minHeight: 26,
  },
  model_scoresThText: {
    fontSize: 10,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  model_scoresTr: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    borderStyle: "solid",
    paddingVertical: 4,
    paddingHorizontal: 5,
    minHeight: 28,
  },
  model_scoresTrBest: {
    borderLeftWidth: 2,
    borderLeftColor: "#22C55E",
    paddingLeft: 4,
    backgroundColor: "#F7FDF9",
  },
  model_scoresTrWorst: {
    borderLeftWidth: 2,
    borderLeftColor: LD.color.risk,
    paddingLeft: 4,
    backgroundColor: "#FFF7F7",
  },
  model_scoresRowBg: {
    backgroundColor: "#FFFFFF",
  },
  model_scoresRowBgAlt: {
    backgroundColor: "#FAFAFA",
  },
  model_scoresTd: {
    fontSize: 10,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: 1.35,
  },
  model_scoresTdEmphasis: {
    fontSize: 10,
    fontFamily: LD.font.sansBold,
    color: "#111111",
    lineHeight: 1.35,
  },
  model_scoresTdDeltaStrong: {
    fontSize: 10,
    fontFamily: LD.font.sansBold,
    color: "#15803D",
    lineHeight: 1.35,
  },
  model_scoresTdDeltaWeak: {
    fontSize: 10,
    fontFamily: LD.font.sansBold,
    color: LD.color.risk,
    lineHeight: 1.35,
  },
  model_scoresColModel: { width: "30%" },
  model_scoresColScore: { width: "14%" },
  model_scoresColDelta: { width: "18%" },
  model_scoresColSignal: { width: "22%" },
  model_scoresColProfile: { width: "16%" },
  model_profileTrack: {
    flexDirection: "row",
    height: 4,
    width: "100%",
    maxWidth: 52,
  },
  model_profileFill: {
    height: 4,
    backgroundColor: LD.color.accent,
  },
  model_profileRest: {
    height: 4,
    backgroundColor: LD.color.rule,
  },
  model_scoresTension: {
    fontSize: 8,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.snug,
    marginTop: LD.space.sm,
    marginBottom: LD.space.xs,
    maxWidth: "100%",
  },
  model_scoresFoot: {
    fontSize: 10.5,
    fontFamily: LD.font.sans,
    color: "#374151",
    lineHeight: 1.55,
    marginTop: LD.space.xs,
    maxWidth: "100%",
  },
  model_takeawayLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.sm,
  },
  model_takeaway: {
    fontSize: LD.size.caption,
    color: LD.color.ink3,
    maxHeight: 36,
    overflow: "hidden",
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
  },
  model_implicationAction: {
    fontSize: 9,
    fontFamily: LD.font.sansBold,
    color: "#111111",
    lineHeight: 1.5,
    marginTop: LD.space.sm,
    maxWidth: "100%",
  },

  /* Evidence — stacked bands (Performance / Competitive-style hierarchy) */
  ev_strengthBand: {
    width: "100%",
    marginBottom: LD.space.lg,
    paddingTop: LD.space.md,
    paddingBottom: LD.space.md,
    borderTopWidth: LD.border.accentRule,
    borderTopColor: LD.color.accent,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  ev_riskBand: {
    width: "100%",
    marginBottom: LD.space.lg,
    paddingTop: LD.space.md,
    paddingBottom: LD.space.md,
    borderTopWidth: LD.border.accentRule,
    borderTopColor: LD.color.risk,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  ev_bandHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: LD.space.md,
  },
  ev_bandStripeS: {
    width: 3,
    height: 14,
    backgroundColor: LD.color.accent,
    marginRight: LD.space.sm,
  },
  ev_bandStripeR: {
    width: 3,
    height: 14,
    backgroundColor: LD.color.risk,
    marginRight: LD.space.sm,
  },
  ev_bandHeading: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    flex: 1,
  },
  ev_bandMeta: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    textAlign: "right" as const,
    maxWidth: "42%",
  },
  ev_promptShell: {
    backgroundColor: LD.color.surface2,
    borderWidth: 1,
    borderColor: "#E8E8E8",
    borderStyle: "solid",
    paddingHorizontal: LD.space.sm,
    paddingVertical: LD.space.sm,
    marginBottom: LD.space.md,
  },
  ev_promptKicker: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs,
  },
  ev_promptBody: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    fontStyle: "italic",
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
  },
  ev_responseKicker: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  ev_metaTable: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderStyle: "solid",
    overflow: "hidden",
    marginBottom: LD.space.md,
  },
  ev_metaTr: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    borderStyle: "solid",
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  ev_metaTrLast: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  ev_metaKey: {
    width: "36%",
    fontSize: 8.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    lineHeight: 1.4,
    paddingRight: LD.space.xs,
  },
  ev_metaVal: {
    flex: 1,
    fontSize: 8.5,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: 1.45,
  },
  ev_excerptShell: {
    paddingLeft: LD.space.md,
    paddingVertical: LD.space.sm,
    marginBottom: LD.space.sm,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.ink3,
    backgroundColor: LD.color.surface2,
  },
  ev_excerptKicker: {
    fontSize: 7.5,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  ev_quote: {
    paddingLeft: LD.space.md,
    paddingVertical: LD.space.sm,
    marginBottom: LD.space.md,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.ink3,
  },
  ev_quoteText: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  ev_quoteLead: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.sm,
  },
  ev_quoteDetail: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.sm,
  },
  ev_quoteImpact: {
    fontSize: LD.size.caption,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
  },
  ev_listIntro: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    marginBottom: LD.space.xs,
    marginTop: LD.space.xs,
  },
  ev_bullet: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.xxs,
    paddingLeft: LD.space.sm,
  },
  ev_note: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
    marginTop: LD.space.sm,
    paddingTop: LD.space.sm,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.rule,
  },
  ev_fieldLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs + 1,
    marginTop: LD.space.sm,
  },
  ev_promptText: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    fontStyle: "italic",
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.sm,
  },
  ev_responseExcerpt: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
  },
  ev_brandHit: {
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    backgroundColor: LD.color.accentMuted,
  },

  rec_col: { flexDirection: "column" },
  rec_item: {
    marginBottom: LD.space.lg,
    paddingBottom: LD.space.lg,
    paddingTop: LD.space.xs,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.ink,
    overflow: "hidden",
  },
  rec_itemLast: {
    marginBottom: 0,
    paddingBottom: LD.space.lg,
    paddingTop: LD.space.xs,
    borderBottomWidth: 0,
    overflow: "hidden",
  },
  rec_priority: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  rec_priorityRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: LD.space.xs,
  },
  rec_priorityDot: {
    width: 8,
    height: 8,
    marginRight: 6,
  },
  rec_priorityDotHigh: { backgroundColor: LD.color.risk },
  rec_priorityDotMedium: { backgroundColor: LD.color.accent },
  rec_priorityDotLow: { backgroundColor: LD.color.ink4 },
  rec_priorityLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  rec_priorityRank: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginLeft: LD.space.sm,
  },
  rec_title: {
    fontSize: LD.size.title + 1,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.28,
    lineHeight: LD.lineHeight.snug,
    marginBottom: LD.space.md,
  },
  rec_insight: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.sm,
  },
  rec_label: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs,
    marginTop: LD.space.sm,
  },
  rec_labelFirst: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs,
    marginTop: 0,
  },
  rec_line: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.xxs,
  },
  rec_actionLine: {
    fontSize: LD.size.body,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    marginBottom: LD.space.xxs,
    marginTop: LD.space.xxs,
  },

  data_bandHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: LD.space.sm,
  },
  data_bandTitle: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.2,
  },
  data_bandTitleSecondary: {
    fontSize: LD.size.titleSm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: -0.1,
  },
  data_th: {
    flexDirection: "row",
    borderBottomWidth: LD.border.accentRule,
    borderBottomColor: LD.color.ink,
    alignItems: "center",
    backgroundColor: LD.color.paper,
  },
  data_tr: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: LD.color.paper,
  },
  data_trSignalPositive: {
    borderLeftWidth: 3,
    borderLeftColor: LD.color.accent,
    backgroundColor: LD.color.surface2,
  },
  data_trSignalImprovable: {
    borderLeftWidth: 3,
    borderLeftColor: LD.color.accent,
    backgroundColor: LD.color.paper,
  },
  data_trSignalGap: {
    borderLeftWidth: 3,
    borderLeftColor: LD.color.risk,
    backgroundColor: LD.color.riskMuted,
  },
  data_rateBarTrack: {
    flexDirection: "row",
    height: 3,
    marginTop: 3,
    width: "100%",
  },
  data_rateBarFill: { height: 3, backgroundColor: LD.color.accent },
  data_rateBarRest: { height: 3, backgroundColor: LD.color.rule },
  data_compBarTrack: {
    flexDirection: "row",
    height: 4,
    marginTop: 2,
    width: "100%",
  },
  data_compBarFill: { height: 4, backgroundColor: LD.color.accent },
  data_compBarFillYou: { height: 4, backgroundColor: LD.color.ink },
  data_compBarRest: { height: 4, backgroundColor: LD.color.rule },
  data_thText: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  data_td: {
    fontSize: 7,
    color: LD.color.ink,
    fontFamily: LD.font.sans,
  },
  data_tdMuted: {
    fontSize: 7,
    color: LD.color.ink4,
    fontFamily: LD.font.sans,
  },
  data_sigA: { width: "34%", paddingRight: LD.space.xs, paddingLeft: LD.space.xs },
  data_sigB: { width: "10%" },
  data_sigC: { width: "18%" },
  data_sigStack: {
    width: "18%",
    flexDirection: "column",
    justifyContent: "center",
    paddingRight: LD.space.xs,
  },
  data_sigD: { width: "12%" },
  data_sigE: { width: "26%" },
  data_compA: { width: "26%", paddingRight: LD.space.xs, paddingLeft: LD.space.xs },
  data_compMentionsCol: {
    width: "12%",
    flexDirection: "column",
    justifyContent: "center",
    paddingRight: 2,
  },
  data_compB: { width: "12%" },
  data_compC: { width: "20%" },
  data_compD: { width: "16%" },
  data_compE: { width: "26%" },

  close_block: { marginBottom: LD.space.xl, overflow: "hidden" },
  close_blockTight: { marginBottom: LD.space.md, overflow: "hidden" },
  close_h_exec: {
    fontSize: LD.size.titleSm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.1,
    marginBottom: LD.space.md,
    paddingBottom: LD.space.xs,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  close_phaseTitle: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    marginBottom: LD.space.xxs + 1,
  },
  close_phaseBody: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  close_h_method: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.sm,
  },
  close_methodBody: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  close_h_next: {
    fontSize: LD.size.display2,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.45,
    marginBottom: LD.space.md,
    lineHeight: LD.lineHeight.tight,
  },
  close_nextBody: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  close_logWrap: {
    marginTop: LD.space.md,
    paddingTop: LD.space.sm,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.rule,
  },
  close_logEyebrow: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.sm,
  },
  close_logTh: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
    alignItems: "center",
    backgroundColor: LD.color.paper,
  },
  close_logTr: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
    alignItems: "center",
    paddingVertical: 4,
    minHeight: 16,
    backgroundColor: LD.color.paper,
  },
  close_logCell: {
    fontSize: LD.size.micro,
    color: LD.color.ink4,
    fontFamily: LD.font.sans,
    lineHeight: LD.lineHeight.normal,
  },
  close_logCellMuted: {
    fontSize: 6,
    color: LD.color.ink4,
    fontFamily: LD.font.sans,
    lineHeight: LD.lineHeight.normal,
    marginTop: 2,
  },
  close_logThText: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: 0.12,
    textTransform: "uppercase",
  },
  close_c1: { width: "6%", paddingLeft: 2 },
  close_c2: { width: "16%", paddingRight: 2 },
  close_c3: { width: "12%" },
  close_c4: { width: "16%" },
  close_c5: { width: "50%", paddingRight: 2 },
});
