import { StyleSheet } from "@react-pdf/renderer";
import { PDF_PAGE_HEIGHT, PDF_PAGE_WIDTH } from "../theme";
import { LD } from "./lockedDesignTokens";

/**
 * Locked report: editorial hierarchy — rules, type contrast, minimal containment.
 */
export const lockedStyles = StyleSheet.create({
  cover_page: {
    width: PDF_PAGE_WIDTH,
    height: PDF_PAGE_HEIGHT,
    fontFamily: LD.font.sans,
    backgroundColor: LD.color.paper,
    position: "relative",
  },
  cover_center: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: LD.space.xxxl,
    paddingTop: 96,
    paddingBottom: 72,
  },
  cover_rule: {
    width: 56,
    height: LD.border.accentRule,
    backgroundColor: LD.color.ink,
    marginBottom: LD.space.xl,
  },
  cover_title: {
    fontSize: LD.size.coverPoster,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    textAlign: "center",
    letterSpacing: -1.1,
    lineHeight: LD.lineHeight.tight,
    marginBottom: LD.space.xl,
    maxWidth: "100%",
  },
  cover_client: {
    fontSize: LD.size.coverClient,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    textAlign: "center",
    lineHeight: LD.lineHeight.normal,
    marginBottom: LD.space.md,
  },
  cover_date: {
    fontSize: LD.size.coverDate,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    textAlign: "center",
    lineHeight: LD.lineHeight.relaxed,
    letterSpacing: 0.12,
  },

  /* ——— Narrative stack (argument spine on every page) ——— */
  nar_stack: {
    marginBottom: LD.space.lg,
    paddingBottom: LD.space.sm,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  nar_stackAfter: {
    marginTop: LD.space.md,
    marginBottom: 0,
    paddingTop: LD.space.sm + 2,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.rule,
  },
  nar_stackCompact: {
    marginBottom: LD.space.sm + 2,
  },
  nar_stackCover: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  nar_headline: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.22,
    lineHeight: LD.lineHeight.tight,
    marginBottom: LD.space.sm + 2,
  },
  nar_headlineCompact: {
    fontSize: LD.size.titleSm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.12,
    lineHeight: LD.lineHeight.snug,
    marginBottom: LD.space.xs + 2,
  },
  nar_interpretation: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.xs + 2,
  },
  nar_interpretationCompact: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.normal,
    marginBottom: LD.space.xs,
  },
  nar_implication: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.editorial,
    marginBottom: LD.space.xs,
  },
  nar_implicationCompact: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.normal,
    marginBottom: 0,
  },
  nar_action: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    marginTop: LD.space.xxs,
  },
  nar_actionCompact: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    marginTop: LD.space.xxs,
  },
  toc_framing: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.xl,
    maxWidth: "100%",
  },

  perf_opening: {
    fontSize: LD.size.body,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.sm,
    maxWidth: "100%",
  },
  perf_transparency: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.normal,
    marginBottom: LD.space.lg,
    maxWidth: "100%",
  },
  perf_heroRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: LD.space.lg,
  },
  perf_heroDial: {
    width: 200,
    marginRight: LD.space.lg,
  },
  perf_heroAside: {
    flex: 1,
    paddingTop: LD.space.sm,
  },
  perf_scoreContext: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.snug,
    marginTop: LD.space.sm,
    maxWidth: "100%",
  },
  perf_metricHint: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.normal,
    marginTop: LD.space.xxs + 1,
    maxWidth: "100%",
  },
  nar_inaction: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.editorial,
    marginTop: LD.space.xs,
  },

  eyebrow: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  sectionTitle: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.2,
    marginBottom: LD.space.sm,
  },
  bandCaption: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.editorial,
    marginBottom: LD.space.md,
    maxHeight: 28,
  },
  bandCaptionLead: {
    fontSize: LD.size.body,
    fontFamily: LD.font.sans,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.md,
    maxHeight: 32,
  },
  body: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
  },
  bodyMuted: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  bodyQuiet: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  caption: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
  },
  labelStrong: {
    fontSize: LD.size.label,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
  },

  divider: {
    height: LD.border.hairline,
    backgroundColor: LD.color.rule,
    marginVertical: LD.space.sm,
  },
  dividerStrong: {
    height: LD.border.accentRule,
    backgroundColor: LD.color.ink,
    marginVertical: LD.space.md,
  },

  card: {
    backgroundColor: LD.color.paper,
    borderWidth: LD.border.hairline,
    borderColor: LD.color.ink,
    overflow: "hidden",
  },
  cardFilled: {
    backgroundColor: LD.color.paper,
    borderWidth: LD.border.hairline,
    borderColor: LD.color.rule,
    overflow: "hidden",
  },

  toc_row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    paddingVertical: LD.space.sm + 3,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  toc_title: {
    flex: 1,
    paddingRight: LD.space.xl,
    fontSize: LD.size.tocTitle,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    letterSpacing: -0.08,
  },
  toc_page: {
    width: 36,
    textAlign: "right",
    fontSize: LD.size.tocPage,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
  },

  /* Performance — open hero, metrics as ruled band */
  perf_hero: {
    marginBottom: LD.space.xxxl,
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  perf_scoreMark: {
    width: 52,
    height: LD.border.accentRule,
    backgroundColor: LD.color.ink,
    marginTop: LD.space.lg,
  },
  perf_score: {
    fontSize: LD.size.commandScore,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -2.2,
    lineHeight: LD.lineHeight.tight,
  },
  perf_status: {
    fontSize: LD.size.caption,
    color: LD.color.ink3,
    marginTop: LD.space.sm,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
  },
  perf_metricsBand: {
    borderTopWidth: LD.border.accentRule,
    borderTopColor: LD.color.ink,
    paddingTop: LD.space.md,
    marginBottom: LD.space.xl,
  },
  perf_metricsRow: {
    flexDirection: "row",
  },
  perf_metricCell: {
    flex: 1,
    marginRight: 0,
    paddingVertical: LD.space.sm + 2,
    paddingHorizontal: LD.space.sm,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.rule,
    justifyContent: "flex-start",
  },
  perf_metricCellFirst: {
    flex: 1,
    marginRight: 0,
    paddingVertical: LD.space.sm + 2,
    paddingHorizontal: LD.space.sm,
    borderLeftWidth: 0,
    justifyContent: "flex-start",
  },
  perf_metricCellLast: {
    flex: 1,
    marginRight: 0,
    paddingVertical: LD.space.sm + 2,
    paddingHorizontal: LD.space.sm,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.rule,
    justifyContent: "flex-start",
  },
  perf_metricLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs + 1,
  },
  perf_metricValue: {
    fontSize: LD.size.metricSecondary,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    letterSpacing: 0,
  },
  perf_metricCellStrong: {
    borderTopWidth: 3,
    borderTopColor: LD.color.accent,
  },
  perf_metricCellModerate: {
    borderTopWidth: 3,
    borderTopColor: LD.color.ink3,
  },
  perf_metricCellWeak: {
    borderTopWidth: 3,
    borderTopColor: LD.color.risk,
  },
  perf_metricValueStrong: { color: LD.color.ink },
  perf_metricValueModerate: { color: LD.color.ink2 },
  perf_metricValueWeak: { color: LD.color.risk },
  perf_support: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    marginTop: LD.space.lg,
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
    maxWidth: "100%",
  },

  /* Competitive — signal strips + sharp table */
  comp_tableIntro: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.sm,
    maxWidth: "100%",
  },
  comp_integrityNote: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    fontStyle: "italic",
    marginBottom: LD.space.lg,
    lineHeight: LD.lineHeight.normal,
  },
  comp_alertsRow: { flexDirection: "row", marginBottom: LD.space.xl },
  comp_alert: {
    flex: 1,
    marginRight: LD.space.md,
    paddingVertical: LD.space.sm + 2,
    paddingHorizontal: LD.space.sm + 2,
    borderLeftWidth: LD.border.accentRule,
    borderLeftColor: LD.color.ink,
    overflow: "hidden",
  },
  comp_alertLast: {
    flex: 1,
    marginRight: 0,
    paddingVertical: LD.space.sm + 2,
    paddingHorizontal: LD.space.sm + 2,
    borderLeftWidth: LD.border.accentRule,
    borderLeftColor: LD.color.ink,
    overflow: "hidden",
  },
  comp_alertEyebrow: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  comp_alertBody: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    fontFamily: LD.font.sans,
  },
  comp_tableTh: {
    flexDirection: "row",
    borderBottomWidth: LD.border.accentRule,
    borderBottomColor: LD.color.ink,
    alignItems: "center",
    backgroundColor: LD.color.paper,
  },
  comp_tableTr: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: LD.color.paper,
  },
  comp_tableTrClient: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.ink,
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: LD.color.surface2,
  },
  comp_thText: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  comp_td: { fontSize: LD.size.bodySm, color: LD.color.ink, fontFamily: LD.font.sans },
  comp_tdMuted: { fontSize: LD.size.bodySm, color: LD.color.ink3, fontFamily: LD.font.sans },
  comp_tdClient: { fontSize: LD.size.bodySm, color: LD.color.ink, fontFamily: LD.font.sansBold },
  comp_cellName: { width: "34%", paddingRight: LD.space.xs, paddingLeft: LD.space.xs },
  comp_cellNum: { width: "14%" },
  comp_cellRate: { width: "18%" },
  comp_cellRank: { width: "14%" },
  comp_cellFlag: { width: "20%" },

  /* Model — fracture as dominant ruled block; grid as register */
  model_fractureShell: {
    marginBottom: LD.space.xxxl,
    paddingBottom: LD.space.lg,
    borderBottomWidth: LD.border.accentRule,
    borderBottomColor: LD.color.ink,
    overflow: "hidden",
  },
  model_fractureEyebrow: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.md,
  },
  model_fractureRow: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  model_pole: {
    flex: 1,
    paddingVertical: LD.space.xs,
    paddingHorizontal: LD.space.sm,
    overflow: "hidden",
  },
  model_poleBest: {
    borderLeftWidth: LD.border.accentRule,
    borderLeftColor: LD.color.accent,
    marginRight: LD.space.md,
    paddingLeft: LD.space.md,
  },
  model_poleWorst: {
    borderLeftWidth: LD.border.accentRule,
    borderLeftColor: LD.color.risk,
    marginRight: 0,
    paddingLeft: LD.space.md,
  },
  model_poleLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  model_poleName: {
    fontSize: LD.size.titleSm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.15,
    marginBottom: LD.space.xxs,
  },
  model_poleScore: {
    fontSize: LD.size.display2,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.5,
    lineHeight: LD.lineHeight.tight,
  },
  model_gapColumn: {
    width: 72,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: LD.space.xs,
  },
  model_gapLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs,
  },
  model_gapValue: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.risk,
    letterSpacing: -0.3,
    lineHeight: LD.lineHeight.tight,
  },
  model_gapCaption: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink3,
    marginTop: LD.space.xxs,
    textAlign: "center",
    lineHeight: LD.lineHeight.snug,
  },
  model_cell: {
    flex: 1,
    marginRight: LD.space.sm,
    paddingVertical: LD.space.sm,
    paddingHorizontal: LD.space.xs + 2,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.ink,
    overflow: "hidden",
  },
  model_cellLast: {
    flex: 1,
    marginRight: 0,
    paddingVertical: LD.space.sm,
    paddingHorizontal: LD.space.xs + 2,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.ink,
    overflow: "hidden",
  },
  model_cellEmpty: {
    flex: 1,
    marginRight: LD.space.sm,
    paddingVertical: LD.space.sm,
    paddingHorizontal: LD.space.xs + 2,
    borderBottomWidth: 0,
    overflow: "hidden",
  },
  model_cellEmptyLast: {
    flex: 1,
    marginRight: 0,
    paddingVertical: LD.space.sm,
    paddingHorizontal: LD.space.xs + 2,
    borderBottomWidth: 0,
    overflow: "hidden",
  },
  model_cellLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs + 1,
  },
  model_name: {
    fontSize: LD.size.caption,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    marginBottom: LD.space.xxs + 1,
  },
  model_score: {
    fontSize: LD.size.lead,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.2,
  },
  model_scoreBarTrack: {
    flexDirection: "row",
    height: 4,
    marginTop: LD.space.sm,
    width: "100%",
  },
  model_scoreBarFill: {
    backgroundColor: LD.color.accent,
    height: 4,
  },
  model_scoreBarRest: {
    backgroundColor: LD.color.rule,
    height: 4,
  },
  model_takeawayLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.sm,
  },
  model_takeaway: {
    fontSize: LD.size.caption,
    color: LD.color.ink3,
    maxHeight: 36,
    overflow: "hidden",
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
  },

  /* Evidence — excerpt columns, not cards */
  ev_cardStrength: {
    flex: 1,
    marginRight: LD.space.lg,
    paddingTop: LD.space.sm,
    paddingRight: LD.space.sm,
    borderTopWidth: LD.border.accentRule,
    borderTopColor: LD.color.accent,
    overflow: "hidden",
  },
  ev_cardRisk: {
    flex: 1,
    marginRight: 0,
    paddingTop: LD.space.sm,
    paddingRight: 0,
    borderTopWidth: LD.border.accentRule,
    borderTopColor: LD.color.risk,
    overflow: "hidden",
  },
  ev_badge: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    marginBottom: LD.space.md,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  ev_badgeHint: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    marginBottom: LD.space.md,
    lineHeight: LD.lineHeight.snug,
  },
  ev_quote: {
    paddingLeft: LD.space.md,
    paddingVertical: LD.space.sm,
    marginBottom: LD.space.md,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.ink3,
  },
  ev_quoteText: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  ev_quoteLead: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.sm,
  },
  ev_quoteDetail: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.sm,
  },
  ev_quoteImpact: {
    fontSize: LD.size.caption,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
  },
  ev_listIntro: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink2,
    marginBottom: LD.space.xs,
    marginTop: LD.space.xs,
  },
  ev_bullet: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.xxs,
    paddingLeft: LD.space.sm,
  },
  ev_note: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.editorial,
    fontFamily: LD.font.sans,
  },
  ev_fieldLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs + 1,
    marginTop: LD.space.sm,
  },
  ev_promptText: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    fontStyle: "italic",
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    marginBottom: LD.space.sm,
  },
  ev_responseExcerpt: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sans,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    paddingLeft: LD.space.sm,
    borderLeftWidth: LD.border.hairline,
    borderLeftColor: LD.color.ink3,
    marginBottom: LD.space.sm,
  },

  rec_col: { flexDirection: "column" },
  rec_item: {
    marginBottom: LD.space.lg,
    paddingBottom: LD.space.md,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.ink,
    overflow: "hidden",
  },
  rec_itemLast: {
    marginBottom: 0,
    paddingBottom: LD.space.md,
    borderBottomWidth: 0,
    overflow: "hidden",
  },
  rec_priority: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xs,
  },
  rec_priorityRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: LD.space.xs,
  },
  rec_priorityDot: {
    width: 8,
    height: 8,
    marginRight: 6,
  },
  rec_priorityDotHigh: { backgroundColor: LD.color.risk },
  rec_priorityDotMedium: { backgroundColor: LD.color.accent },
  rec_priorityDotLow: { backgroundColor: LD.color.ink4 },
  rec_priorityLabel: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  rec_priorityRank: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sans,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginLeft: LD.space.sm,
  },
  rec_title: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.25,
    lineHeight: LD.lineHeight.snug,
    marginBottom: LD.space.sm + 2,
  },
  rec_insight: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink3,
    lineHeight: LD.lineHeight.normal,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.md,
  },
  rec_label: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs,
    marginTop: LD.space.sm,
  },
  rec_labelFirst: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.xxs,
    marginTop: 0,
  },
  rec_line: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    fontFamily: LD.font.sans,
    marginBottom: LD.space.xxs,
  },
  rec_actionLine: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.snug,
    marginBottom: LD.space.xxs,
  },

  data_bandHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: LD.space.sm,
  },
  data_bandTitle: {
    fontSize: LD.size.title,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.2,
  },
  data_bandTitleSecondary: {
    fontSize: LD.size.titleSm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: -0.1,
  },
  data_th: {
    flexDirection: "row",
    borderBottomWidth: LD.border.accentRule,
    borderBottomColor: LD.color.ink,
    alignItems: "center",
    backgroundColor: LD.color.paper,
  },
  data_tr: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: LD.color.paper,
  },
  data_thText: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink3,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
  },
  data_td: {
    fontSize: 7,
    color: LD.color.ink,
    fontFamily: LD.font.sans,
  },
  data_tdMuted: {
    fontSize: 7,
    color: LD.color.ink4,
    fontFamily: LD.font.sans,
  },
  data_sigA: { width: "38%", paddingRight: LD.space.xs, paddingLeft: LD.space.xs },
  data_sigB: { width: "12%" },
  data_sigC: { width: "14%" },
  data_sigD: { width: "12%" },
  data_sigE: { width: "24%" },
  data_compA: { width: "28%", paddingRight: LD.space.xs, paddingLeft: LD.space.xs },
  data_compB: { width: "14%" },
  data_compC: { width: "14%" },
  data_compD: { width: "18%" },
  data_compE: { width: "26%" },

  close_block: { marginBottom: LD.space.xl, overflow: "hidden" },
  close_blockTight: { marginBottom: LD.space.md, overflow: "hidden" },
  close_h_exec: {
    fontSize: LD.size.titleSm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.1,
    marginBottom: LD.space.md,
    paddingBottom: LD.space.xs,
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
  },
  close_phaseTitle: {
    fontSize: LD.size.bodySm,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    marginBottom: LD.space.xxs + 1,
  },
  close_phaseBody: {
    fontSize: LD.size.bodySm,
    color: LD.color.ink2,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  close_h_method: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.sm,
  },
  close_methodBody: {
    fontSize: LD.size.caption,
    color: LD.color.ink4,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  close_h_next: {
    fontSize: LD.size.display2,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink,
    letterSpacing: -0.45,
    marginBottom: LD.space.md,
    lineHeight: LD.lineHeight.tight,
  },
  close_nextBody: {
    fontSize: LD.size.body,
    color: LD.color.ink,
    lineHeight: LD.lineHeight.relaxed,
    fontFamily: LD.font.sans,
  },
  close_logWrap: {
    marginTop: LD.space.md,
    paddingTop: LD.space.sm,
    borderTopWidth: LD.border.hairline,
    borderTopColor: LD.color.rule,
  },
  close_logEyebrow: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: LD.trackEyebrow,
    textTransform: "uppercase",
    marginBottom: LD.space.sm,
  },
  close_logTh: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
    alignItems: "center",
    backgroundColor: LD.color.paper,
  },
  close_logTr: {
    flexDirection: "row",
    borderBottomWidth: LD.border.hairline,
    borderBottomColor: LD.color.rule,
    alignItems: "center",
    paddingVertical: 4,
    minHeight: 16,
    backgroundColor: LD.color.paper,
  },
  close_logCell: {
    fontSize: LD.size.micro,
    color: LD.color.ink4,
    fontFamily: LD.font.sans,
    lineHeight: LD.lineHeight.normal,
  },
  close_logCellMuted: {
    fontSize: 6,
    color: LD.color.ink4,
    fontFamily: LD.font.sans,
    lineHeight: LD.lineHeight.normal,
    marginTop: 2,
  },
  close_logThText: {
    fontSize: LD.size.micro,
    fontFamily: LD.font.sansBold,
    color: LD.color.ink4,
    letterSpacing: 0.12,
    textTransform: "uppercase",
  },
  close_c1: { width: "6%", paddingLeft: 2 },
  close_c2: { width: "16%", paddingRight: 2 },
  close_c3: { width: "12%" },
  close_c4: { width: "16%" },
  close_c5: { width: "50%", paddingRight: 2 },
});
