"use client";

import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-bg">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <header className="mb-10">
          <h1 className="text-3xl font-bold tracking-tight text-text">Terms of Service</h1>
          <p className="mt-2 text-sm text-text-3">VRTL Score — Version 1.1</p>
          <p className="mt-1 text-sm text-text-3">Last updated / Effective Date: February 3, 2026</p>
        </header>

        <div className="prose prose-slate max-w-none">
          <p>
            These Terms of Service (“Terms”) govern your access to and use of VRTL Score (“VRTL,” “we,” “us,” or
            “our”), including our website, application, and related services (collectively, the “Service”). By
            accessing or using the Service, you agree to these Terms. If you are entering these Terms on behalf of a
            company or other legal entity, you represent that you have the authority to bind that entity.
          </p>

          <h2>Definitions</h2>
          <p>
            <strong>“Service”</strong> means our website, application, tools, reports, scores, and related features.
          </p>
          <p>
            <strong>“User Data”</strong> means any data, content, or information you submit to or through the Service.
          </p>
          <p>
            <strong>“You”</strong> or <strong>“User”</strong> means the individual or entity accessing or using the
            Service.
          </p>

          <h2>1. The Service</h2>
          <p>
            VRTL Score provides tools to measure and report how brands appear in responses generated by third-party AI
            models. The Service is provided for informational and analytical purposes only.
          </p>
          <p>
            We do not control, operate, own, or guarantee the behavior, outputs, availability, or changes to any
            third-party AI models (e.g., those from OpenAI, Anthropic, xAI, etc.). AI outputs may be inaccurate,
            incomplete, biased, or change without notice.
          </p>

          <h2>2. Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and for all activity
            under your account. You must provide accurate, complete, and current information when creating an account.
          </p>
          <p>We reserve the right to suspend or terminate accounts for violations of these Terms, suspected fraud, or at our discretion.</p>

          <h2>3. Use Restrictions</h2>
          <p>You agree not to:</p>
          <ul>
            <li>misuse, interfere with, overburden, or disrupt the Service;</li>
            <li>attempt to reverse engineer, decompile, disassemble, or extract source code;</li>
            <li>resell, sublicense, rent, lease, or commercially exploit the Service without our written permission;</li>
            <li>use the Service in violation of applicable laws or third-party rights;</li>
            <li>
              use the Service to train, fine-tune, develop, or improve competing AI models, or to scrape/extract
              outputs for such purposes (this violates these Terms and may degrade Service quality or harm our
              algorithms);
            </li>
            <li>submit User Data that is unlawful, infringing, harmful, or violates third-party rights.</li>
          </ul>

          <h2>4. Data and Content</h2>
          <p>
            You retain ownership of your User Data. By submitting User Data, you grant us a worldwide, non-exclusive,
            royalty-free license to use, process, store, and analyze it solely to provide, maintain, improve, and
            support the Service (including generating reports/scores).
          </p>
          <p>
            We may use aggregated/anonymized data for analytics and improvements. Outputs (reports, scores, analyses)
            are provided “as is” and do not constitute professional, legal, financial, marketing, or other advice.
          </p>
          <p>
            Our handling of personal data is governed by our{" "}
            <Link className="text-text underline underline-offset-4" href="/privacy">
              Privacy Policy
            </Link>
            , incorporated herein.
          </p>

          <h2>5. No Guarantees</h2>
          <p>VRTL Score does not guarantee:</p>
          <ul>
            <li>any specific rankings, mentions, visibility, or performance in third-party AI systems;</li>
            <li>the accuracy, completeness, reliability, or timeliness of AI-generated outputs or Service results;</li>
            <li>any business, marketing, financial, or other outcomes from using the Service.</li>
          </ul>
          <p>Third-party AI behavior may change unpredictably.</p>

          <h2>6. Intellectual Property</h2>
          <p>
            All software, branding, materials, and outputs generated by us (excluding your User Data) are owned by us
            or our licensors and protected by intellectual property laws. We grant you a limited, non-exclusive,
            non-transferable, non-sublicensable license during your subscription term to use Service outputs (including
            reports, scores, and analyses) for your internal business purposes and for client-facing reporting in the
            ordinary course of your business (e.g., sharing customized reports with your clients as part of your
            services). You may not resell, redistribute, or commercially exploit outputs on a standalone basis, or use
            them to create derivative products/services without our written permission. All other rights are reserved.
          </p>
          <p>
            Use of VRTL Score branding, logos, or any white-labeled versions of the Service or outputs is subject to
            your subscription plan limitations, our prior written approval, and any additional guidelines we provide.
          </p>

          <h2>7. Termination</h2>
          <p>
            You may stop using the Service at any time. We may suspend or terminate your access for violations of these
            Terms, non-payment, or if required by law, with or without notice.
          </p>

          <h2>8. Disclaimer of Warranties</h2>
          <p>
            The Service is provided “as is” and “as available.” We disclaim all warranties, express or implied,
            including merchantability, fitness for a particular purpose, non-infringement, and accuracy of results.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, VRTL Score, its affiliates, officers, and employees shall not be
            liable for any indirect, incidental, consequential, special, punitive, or exemplary damages (including lost
            profits, data, or business opportunities), even if advised of the possibility. Our total liability shall not
            exceed the fees paid by you in the 12 months preceding the claim.
          </p>

          <h2>10. Governing Law and Dispute Resolution</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware, without regard to its conflict-of-laws
            principles.
          </p>
          <p>
            Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be
            resolved exclusively by binding arbitration administered by the American Arbitration Association (AAA) under
            its Commercial Arbitration Rules. The arbitration shall be conducted by a single arbitrator in Wilmington,
            Delaware (or remotely via video conference if agreed). Judgment on the award may be entered in any court
            having jurisdiction.
          </p>
          <p>
            You and VRTL Score waive any right to a jury trial or to participate in a class action, mass arbitration, or
            other representative proceeding. This waiver applies whether in arbitration or court. Either party may seek
            injunctive relief in court for misuse of intellectual property or confidentiality breaches. You may opt out
            of arbitration by sending written notice to <a href="mailto:contact@vrtlscore.com">contact@vrtlscore.com</a>{" "}
            within 30 days of first agreeing to these Terms.
          </p>

          <h2>11. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. We will post changes on our website and notify registered users
            via email or in-app notice. Continued use after the effective date (at least 30 days after posting)
            constitutes acceptance.
          </p>

          <h2>12. Contact</h2>
          <p>
            Questions about these Terms may be sent to:{" "}
            <a href="mailto:contact@vrtlscore.com">contact@vrtlscore.com</a>
          </p>

          <h2>13. Payment and Fees</h2>
          <p>
            If you subscribe to a paid tier, you agree to pay the fees listed on our pricing page. Fees are in USD,
            non-refundable (except as required by law), and charged via our third-party processor (e.g., Stripe).
            Subscriptions auto-renew monthly/annually unless canceled at least 24 hours before renewal. You may cancel
            via your account settings. We may change fees or tiers with 30 days&apos; notice. You are responsible for all
            taxes. Late payments accrue interest at 1.5% per month or the maximum allowed by law.
          </p>

          <h2>14. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless VRTL Score, its affiliates, officers, directors, and
            employees from any claims, losses, damages, liabilities, costs (including reasonable attorneys&apos; fees)
            arising from: (a) your violation of these Terms; (b) your User Data infringing third-party rights or being
            unlawful; or (c) your use of the Service in violation of laws.
          </p>

          <h2>15. Service Levels and Support</h2>
          <p>
            We aim to provide the Service with commercially reasonable efforts but do not guarantee uninterrupted or
            error-free access. Downtime may occur due to maintenance, third-party issues (including AI model outages),
            or force majeure. Support is available via email during business hours (9 AM–5 PM EST, Mon–Fri) with target
            response times of up to 48 hours (these are targets, not guarantees). Premium tiers may include priority
            support. No credits/refunds for downtime unless in a separate agreement.
          </p>

          <h2>16. Force Majeure</h2>
          <p>
            Neither party is liable for delays or failures due to events beyond reasonable control (e.g., acts of God,
            pandemics, cyberattacks, government actions).
          </p>

          <h2>17. Severability and Waiver</h2>
          <p>
            If any provision is held invalid or unenforceable, the remainder remains in effect. Failure to enforce any
            right does not waive it.
          </p>

          <h2>18. Assignment</h2>
          <p>
            You may not assign these Terms without our written consent. We may assign them freely (e.g., in a merger,
            acquisition, or sale of assets).
          </p>

          <h2>19. Export Controls</h2>
          <p>
            You agree not to use or export the Service in violation of U.S. export laws, sanctions, or to embargoed
            countries/entities.
          </p>

          <h2>20. DMCA Policy</h2>
          <p>
            We comply with the Digital Millennium Copyright Act. Send infringement notices to{" "}
            <a href="mailto:contact@vrtlscore.com">contact@vrtlscore.com</a> with required details (e.g., description of
            infringement, your contact info, good-faith statement).
          </p>

          <p>
            By using the Service, you acknowledge you&apos;ve read, understood, and agree to these Terms.
          </p>
        </div>
      </div>
    </main>
  );
}

